package alabaster.hearthandharvest.common.registry;

import alabaster.hearthandharvest.HearthAndHarvest;
import net.fabricmc.fabric.api.item.v1.DefaultItemComponentEvents;
import net.hecco.bountifulfares.registry.util.BFRegistries;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.item.component.Compostable;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Hearth and Harvest's composter chances (1.21.1: the NeoForge {@code compostables} data map) and
 * those of the Farmer's Delight items it now carries (FarmersDelightRefabricated's CompostableHelper).
 * 26.3 stores compostability as the {@code minecraft:compostable} item component; chances map onto
 * vanilla's tiers like Bountiful Fares' own (BFRegistries.compostBucketFor).
 * Generated by {@code _porting_tools/hh_data_migrate.py}; merged items are left to their own mod.
 */
public final class HHCompostables {
    private static final Map<String, Float> CHANCES = new LinkedHashMap<>();

    static {
        CHANCES.put("blue_mum", 0.65F);
        CHANCES.put("blueberries", 0.3F);
        CHANCES.put("blueberry_pie", 1.0F);
        CHANCES.put("blueberry_pie_slice", 0.85F);
        CHANCES.put("cabbage", 0.65F);
        CHANCES.put("cabbage_leaf", 0.5F);
        CHANCES.put("cabbage_seeds", 0.3F);
        CHANCES.put("carrot_cake", 1.0F);
        CHANCES.put("carrot_cake_slice", 0.85F);
        CHANCES.put("cherry", 0.65F);
        CHANCES.put("chicken_pot_pie", 1.0F);
        CHANCES.put("chicken_pot_pie_slice", 0.85F);
        CHANCES.put("corn", 0.3F);
        CHANCES.put("corn_husk", 0.3F);
        CHANCES.put("corn_husk_bundle", 0.5F);
        CHANCES.put("corn_kernels", 0.3F);
        CHANCES.put("cotton", 0.65F);
        CHANCES.put("cotton_bale", 0.5F);
        CHANCES.put("cotton_seeds", 0.3F);
        CHANCES.put("grape_pie", 1.0F);
        CHANCES.put("grape_pie_slice", 0.85F);
        CHANCES.put("green_grapes", 0.65F);
        CHANCES.put("hay_rug", 0.3F);
        CHANCES.put("light_blue_mum", 0.65F);
        CHANCES.put("onion", 0.65F);
        CHANCES.put("orange_mum", 0.65F);
        CHANCES.put("peanut", 0.65F);
        CHANCES.put("peanut_butter_pie", 1.0F);
        CHANCES.put("peanut_butter_pie_slice", 0.85F);
        CHANCES.put("pie_crust", 0.65F);
        CHANCES.put("pink_mum", 0.65F);
        CHANCES.put("purple_mum", 0.65F);
        CHANCES.put("raspberry", 0.3F);
        CHANCES.put("raspberry_pie", 1.0F);
        CHANCES.put("raspberry_pie_slice", 0.85F);
        CHANCES.put("red_grapes", 0.65F);
        CHANCES.put("red_mum", 0.65F);
        CHANCES.put("stick_brush", 0.5F);
        CHANCES.put("straw", 0.3F);
        CHANCES.put("sugar_cane_bundle", 0.5F);
        CHANCES.put("sunflower_seeds", 0.3F);
        CHANCES.put("tree_bark", 0.3F);
        CHANCES.put("white_mum", 0.65F);
        CHANCES.put("wild_cabbages", 0.65F);
        CHANCES.put("wild_cotton", 0.65F);
        CHANCES.put("wild_green_grapes", 0.65F);
        CHANCES.put("wild_onions", 0.65F);
        CHANCES.put("wild_peanuts", 0.65F);
        CHANCES.put("wild_red_grapes", 0.65F);
        CHANCES.put("yellow_mum", 0.65F);
    }

    private HHCompostables() {
    }

    public static void register() {
        DefaultItemComponentEvents.MODIFY.register(context -> CHANCES.forEach((path, chance) ->
                context.modify(BuiltInRegistries.ITEM.getValue(HearthAndHarvest.id(path)),
                        builder -> builder.set(DataComponents.COMPOSTABLE, new Compostable(BFRegistries.compostBucketFor(chance))))));
    }
}
