#!/usr/bin/env python3
"""Migrate Hearth and Harvest's 1.21.1 data (NeoForge; generated + hand-written) into this 26.3 bundle,
plus the Farmer's Delight data HH needs (FD is no longer a dependency, see HEARTH_AND_HARVEST_STATUS.md).

Usage: hh_data_migrate.py <hh repo> <fdr 26.3 repo> <fd 1.21 repo> <bf-port dir> <vanilla 26.3 extract> [<data dir>...]
  hh repo:   github.com/AlabasterLeking/Hearth-And-Harvest, branch NeoForge-1.21.1
  fdr repo:  github.com/MehVahdJukaar/FarmersDelightRefabricated, branch fabric/latest/26.3 (615259dd4)
  fd repo:   github.com/vectorwing/FarmersDelight, branch 1.21 (wild cabbage/onion worldgen + biome tags)
  vanilla:   a folder holding the 26.3 jars' data/ and assets/ (vanilla ids for validation)
  data dirs: other data/ folders whose tags exist at runtime (Fabric API's convention tags: the data/
             folders of the fabric-api jars)

Writes under <bf-port>/src/main/resources/data. Reuses data_migrate.py / worldgen_migrate.py rules
(ingredients, loot tables, advancements, 26.3 worldgen) and adds:

Ids (context aware: item, block and fluid ids are remapped separately, since HH's fluids share
names with merged items, e.g. the hearthandharvest:sweet_berry_wine fluid stays)
* Ported FD content: farmersdelight:<x> -> hearthandharvest:<x> for every block/item registered in
  HHModBlocks/HHModItems; FD tags farmersdelight:<t> -> hearthandharvest:<t> (FDTags).
* FD items that already exist in the bundle (user decision 9): tomato -> flavored:red_tomato, tomato
  seeds/crop -> flavored:tomato_seeds/tomato_bush, beef patty -> flavored:cooked_ground_beef (FD's
  patty is cooked), chicken cuts -> flavored:chicken_drumstick (+ cooked), raw pasta ->
  flavored:pasta, apple cider -> flavored:apple_juice, wheat dough -> flavored:dough, knives ->
  flavored:knife, mutton chops -> flavored:mutton_shank, bacon -> flavored:pork_jowl.
* HH items merged into BF/Flavored (decisions 3, 4, 7, 11): see HHRegistryAliases.MERGED_ITEMS.
* Dropped (no counterpart in the bundle): FD rice, skillet, shepherd's pie, stuffed pumpkin, rotten
  tomato, sandy shrub, tomatoes on rope; HH trellises (BF trellises replace them), rotten tomato
  crate, flour bag. Loot entries/tag values naming them are removed; recipes making or needing them
  are skipped (HH's flour bag <-> flour recipes too: BF's flour block has its own).

Recipes
* farmersdelight:cooking/cutting -> hearthandharvest:cooking/cutting (FDR 26.3 field layout, which the
  ported serializers use). Custom ingredients become Fabric ones: hearthandharvest:vintage and
  farmersdelight:item_ability -> {"fabric:type": "hearthandharvest:vintage"/"hearthandharvest:item_ability"},
  neoforge:components -> fabric:components {"base", "components"}.
* neoforge:conditions mod_loaded -> fabric:load_conditions all_mods_loaded (Create, Brewin' and
  Chewin', Botany Pots, Berry Good, Crabber's Delight integration recipes; none of those mods has a
  26.3 Fabric build, so these stay inert and untested).
* Results: {"count": 1, "id": x} -> {"id": x}.
* Merged items keep HH's recipes as extra routes (HH crafting pizza / batter / butter, cask aging of
  the merged wines, mead and pickled beetroot - decision 13).

FD 26.3 data (already 26.3 format) is copied for the ported FD pieces: recipes whose result is a
ported FD item or that only use bundle items (cutting board stripping/flower/meat-free recipes),
block loot tables, tags (filtered to existing ids), farmer trades for cabbages/onions.

Other conversions
* NeoForge biome modifiers: done in code (HHBiomeModifiers), not copied.
* NeoForge compostables data map -> HHCompostables.java (generated by this script);
  global loot modifier cherries_from_cherry_leaves -> HHLootModifiers (code).
* HH's data maps (fluid_bottle, vintage_style) keep their files and NeoForge format (HHDataMaps loader).
* Villager trades (1.21.1: VillagerEvents code) -> 26.3 data-driven villager_trade + trade tags.
* worldgen: farmersdelight:wild_crop -> hearthandharvest:wild_crop (inner placed features in 26.3
  form); farmersdelight:biome_tag placement modifiers dropped (biome selection is HHBiomeModifiers').
  FD 1.21's wild cabbage/onion patches and biome tags are converted the same way.
* Lilliput Lane structure NBT: farmersdelight blocks/block entities -> hearthandharvest ones; FD
  blocks that are not part of the bundle get vanilla stand-ins (stove -> smoker, tatami ->
  bamboo mosaic, rope fence -> oak fence, canvas wall signs -> pale oak/cherry wall signs, wooden
  basket -> barrel, keeping loot tables); HH trellises -> BF trellises (one side per block, plant in
  the block entity; flat-only trellises -> oak trapdoors).
* Tag files whose path Bountiful Fares' datagen also writes (src/main/generated) can't be shipped
  twice in one jar: their entries go to the generated HHTagAdditions.java, which BF's item/block
  tag providers apply. Other tag files that already exist in the bundle are merged (union).
"""
import collections
import copy
import gzip
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
import data_migrate as dm  # noqa: E402
import worldgen_migrate as wm  # noqa: E402

HH = "hearthandharvest"

# ----------------------------------------------------------------------------- id tables

FD_TO_BUNDLE_ITEMS = {
    "farmersdelight:tomato": "flavored:red_tomato",
    "farmersdelight:tomato_seeds": "flavored:tomato_seeds",
    "farmersdelight:beef_patty": "flavored:cooked_ground_beef",
    "farmersdelight:chicken_cuts": "flavored:chicken_drumstick",
    "farmersdelight:cooked_chicken_cuts": "flavored:cooked_chicken_drumstick",
    "farmersdelight:raw_pasta": "flavored:pasta",
    "farmersdelight:apple_cider": "flavored:apple_juice",
    "farmersdelight:wheat_dough": "flavored:dough",
    "farmersdelight:flint_knife": "flavored:knife",
    "farmersdelight:iron_knife": "flavored:knife",
    "farmersdelight:golden_knife": "flavored:knife",
    "farmersdelight:diamond_knife": "flavored:knife",
    "farmersdelight:netherite_knife": "flavored:knife",
    "farmersdelight:mutton_chops": "flavored:mutton_shank",
    "farmersdelight:bacon": "flavored:pork_jowl",
}
FD_TO_BUNDLE_BLOCKS = {
    "farmersdelight:tomatoes": "flavored:tomato_bush",
    "farmersdelight:budding_tomatoes": "flavored:tomato_bush",
}
HH_MERGED_ITEMS = {
    "mead": "bountifulfares:mead_bottle",
    "sweet_berry_wine": "flavored:sweet_berry_wine",
    "glow_berry_wine": "flavored:glow_berry_wine",
    "sweet_berry_juice": "flavored:sweet_berry_juice",
    "glow_berry_juice": "flavored:glow_berry_juice",
    "pizza": "flavored:pizza",
    "pizza_slice": "flavored:pizza_slice",
    "pickled_beetroots": "bountifulfares:pickled_beetroot",
    "flour": "bountifulfares:flour",
    "butter": "flavored:butter",
    "batter": "flavored:batter",
    "chocolate_bar": "flavored:chocolate",
}
HH_MERGED_BLOCKS = {"pizza": "flavored:pizza"}
HH_RENAMES = {"elote": "street_corn", "cheddar_cheese_wheel": "cheese_wheel",
              "unripe_cheddar_cheese_wheel": "unripe_cheese_wheel", "cheddar_cheese_slice": "cheese_slice"}
# Ingredient position: accept any item of the merged kind, like Flavored's migration did for flour.
INGREDIENT_REMAP = {"bountifulfares:flour": "#c:flour"}
DROPPED = {
    "farmersdelight:rice", "farmersdelight:skillet", "farmersdelight:shepherds_pie", "farmersdelight:stuffed_pumpkin",
    "farmersdelight:rotten_tomato", "farmersdelight:sandy_shrub", "farmersdelight:tomatoes_on_rope",
    "hearthandharvest:trellis", "hearthandharvest:bamboo_trellis", "hearthandharvest:stripped_bamboo_trellis",
    "hearthandharvest:grape_trellis", "hearthandharvest:rotten_tomato_crate", "hearthandharvest:flour_bag",
}
SKIP_RECIPES = {"flour_bag", "flour_from_bag"}  # duplicates of BF's flour block recipes

FLUIDS = set()          # hearthandharvest fluid ids (filled from HHModFluids)
KNOWN_ITEMS = set()
KNOWN_BLOCKS = set()
HH_ITEMS = set()
HH_BLOCKS = set()
REPORT = collections.defaultdict(list)


class Dropped(Exception):
    pass


def ns_path(i):
    return i.split(":", 1) if ":" in i else ("minecraft", i)


def norm(i):
    return i if ":" in i else "minecraft:" + i


VANILLA_RENAMES = {"minecraft:chain": "minecraft:iron_chain"}  # renamed after 1.21.1
# Advancements only ("Climbing the Walls": obtain a trellis): HH's trellises became BF's.
ADVANCEMENT_ITEMS = {"hearthandharvest:trellis": "bountifulfares:trellis",
                     "hearthandharvest:bamboo_trellis": "bountifulfares:bamboo_trellis",
                     "hearthandharvest:stripped_bamboo_trellis": "bountifulfares:bamboo_trellis"}


def remap_item(i):
    """Item id -> bundle id; raises Dropped for items with no counterpart."""
    i = VANILLA_RENAMES.get(norm(i), norm(i))
    if i in DROPPED:
        raise Dropped(i)
    ns, p = ns_path(i)
    if ns == "farmersdelight":
        if i in FD_TO_BUNDLE_ITEMS:
            return FD_TO_BUNDLE_ITEMS[i]
        if p in HH_ITEMS:
            return HH + ":" + p
        raise Dropped(i)
    if ns == HH:
        p = HH_RENAMES.get(p, p)
        if p in HH_MERGED_ITEMS:
            return HH_MERGED_ITEMS[p]
        return HH + ":" + p
    return i


def remap_block(i):
    i = VANILLA_RENAMES.get(norm(i), norm(i))
    if i in DROPPED:
        raise Dropped(i)
    ns, p = ns_path(i)
    if ns == "farmersdelight":
        if i in FD_TO_BUNDLE_BLOCKS:
            return FD_TO_BUNDLE_BLOCKS[i]
        if p in HH_BLOCKS:
            return HH + ":" + p
        raise Dropped(i)
    if ns == HH:
        p = HH_RENAMES.get(p, p)
        return HH_MERGED_BLOCKS.get(p, HH + ":" + p)
    return i


def remap_tag(t):
    """A tag id (no '#'). FD's own tags moved to the hearthandharvest namespace (FDTags)."""
    ns, p = ns_path(t)
    if ns == "farmersdelight":
        return HH + ":" + p
    if t == "c:flours":     # HH used c:flours (+ c:flours/wheat, c:flours/corn); BF/Flavored use c:flour
        return t
    return t


def remap_ref(s, kind):
    """'#tag' or id, of kind 'item'/'block'."""
    if s.startswith("#"):
        return "#" + remap_tag(s[1:])
    return remap_item(s) if kind == "item" else remap_block(s)


def check_known(i, kind):
    known = KNOWN_ITEMS if kind == "item" else KNOWN_BLOCKS
    if not i.startswith("#") and i not in known:
        raise Dropped(i)
    return i


# ----------------------------------------------------------------------------- ingredients/recipes

def ingredient(i):
    """1.21.1 ingredient -> 26.3 (string, list of strings, or Fabric custom object)."""
    if isinstance(i, list):
        out = []
        for x in i:
            try:
                out.append(ingredient(x))
            except Dropped as e:
                REPORT["ingredient alternative dropped"].append(str(e))
        if not out:
            raise Dropped("empty ingredient list")
        flat = []
        for x in out:
            if isinstance(x, list):
                flat += x
            elif isinstance(x, dict):
                if len(out) == 1:
                    return x
                raise ValueError("custom ingredient inside a list: %r" % i)
            else:
                flat.append(x)
        return flat[0] if len(flat) == 1 else flat
    if isinstance(i, str):
        r = check_known(remap_ref(i, "item"), "item")
        return INGREDIENT_REMAP.get(r, r)
    t = i.get("type") or i.get("fabric:type")
    if t in ("hearthandharvest:vintage",):
        return {"fabric:type": "hearthandharvest:vintage", "base": ingredient(i["base"]), "vintage": i["vintage"]}
    if t in ("farmersdelight:item_ability", "hearthandharvest:item_ability"):
        return {"fabric:type": "hearthandharvest:item_ability", "action": i["action"]}
    if t == "neoforge:components":
        out = {"fabric:type": "fabric:components", "base": ingredient(i["items"]), "components": i["components"]}
        return out
    if t is not None:
        raise ValueError("unhandled ingredient type %s" % t)
    if "item" in i:
        r = check_known(remap_item(i["item"]), "item")
        return INGREDIENT_REMAP.get(r, r)
    if "tag" in i:
        return "#" + remap_tag(i["tag"])
    raise ValueError("unhandled ingredient %r" % i)


def stack(s, key="id"):
    s = dict(s)
    s[key] = check_known(remap_item(s[key]), "item")
    if s.get("count") == 1:
        del s["count"]
    return s


def conditions_to_fabric(r):
    conds = r.pop("neoforge:conditions", None)
    if not conds:
        return r
    mods = []
    for c in conds:
        if c.get("type") == "neoforge:mod_loaded":
            mods.append(c["modid"])
        else:
            raise ValueError("unhandled condition %r" % c)
    return {"fabric:load_conditions": [{"condition": "fabric:all_mods_loaded", "values": mods}], **r}


INTEGRATION_MODS = {"create", "brewinandchewin", "botanypots", "berry_good", "crabbersdelight"}


FLUID_REMAP = {"minecraft:milk": "hearthandharvest:milk"}  # NeoForge's milk fluid; HH registers its own on Fabric


def recipe(r):
    r = conditions_to_fabric(copy.deepcopy(r))
    for k in ("input_fluid", "result_fluid"):
        if isinstance(r.get(k), dict) and "id" in r[k]:
            r[k]["id"] = FLUID_REMAP.get(r[k]["id"], r[k]["id"])
    cond_mods = set()
    for c in r.get("fabric:load_conditions", []):
        cond_mods.update(c["values"])
    t = r["type"]
    if t.split(":")[0] in INTEGRATION_MODS or cond_mods & INTEGRATION_MODS:
        # Another mod's format / a conditional HH recipe: ids only (formats of those mods unknown on 26.3).
        return remap_loose(r)
    if t in ("farmersdelight:cooking", "farmersdelight:cutting"):
        r["type"] = HH + ":" + t.split(":")[1]
    t = r["type"]
    if "key" in r:
        r["key"] = {k: ingredient(v) for k, v in r["key"].items()}
    for k in ("ingredient", "base", "addition", "template", "tool", "salt", "input"):
        if k in r:
            r[k] = ingredient(r[k])
    if "ingredients" in r:
        r["ingredients"] = [ingredient(x) for x in r["ingredients"]]
    if t == HH + ":cutting":
        out = []
        for res in r["result"]:
            try:
                res = dict(res)
                res["item"] = stack(res["item"])
                out.append(res)
            except Dropped as e:
                REPORT["cutting result dropped"].append(str(e))
        if not out:
            raise Dropped("no cutting results")
        r["result"] = out
    else:
        for k in ("result", "result_item", "container"):
            if k in r and isinstance(r[k], dict):
                r[k] = stack(r[k])
    return r


def remap_loose(o):
    """Remap ids found anywhere (for other mods' recipe formats). Leaves unknown strings alone."""
    if isinstance(o, dict):
        return {k: remap_loose(v) for k, v in o.items()}
    if isinstance(o, list):
        return [remap_loose(v) for v in o]
    if isinstance(o, str) and re.fullmatch(r"(farmersdelight|hearthandharvest):[a-z0-9_/]+", o):
        try:
            return remap_item(o)
        except Dropped:
            return o
    return o


# ----------------------------------------------------------------------------- loot/advancements

def remap_ids_in(o, kind="item"):
    """Remap item ids in advancement/loot predicate structures ("items": str|list, "id", "name")."""
    if isinstance(o, dict):
        out = {}
        for k, v in o.items():
            if k in ("items",) and isinstance(v, str):
                out[k] = check_known(remap_ref(v, "item"), "item")
            elif k in ("items",) and isinstance(v, list) and all(isinstance(x, str) for x in v):
                out[k] = [check_known(remap_ref(x, "item"), "item") for x in v]
            elif k == "blocks" and isinstance(v, (str, list)):
                vs = [v] if isinstance(v, str) else v
                vs = [check_known(remap_ref(x, "block"), "block") for x in vs]
                out[k] = vs[0] if isinstance(v, str) else vs
            elif k == "block" and isinstance(v, str):
                out[k] = check_known(remap_block(v), "block")
            elif k == "id" and isinstance(v, str) and ":" in v and "count" in o or k == "id" and set(o) <= {"id", "count", "components"}:
                out[k] = check_known(remap_item(v), "item")
            elif k == "recipes" or k == "recipe":
                out[k] = v
            elif k == "tag" and isinstance(v, str):
                out[k] = remap_tag(v)
            else:
                out[k] = remap_ids_in(v, kind)
        return out
    if isinstance(o, list):
        return [remap_ids_in(v, kind) for v in o]
    return o


def loot_condition(c):
    c = dict(c)
    if c.get("type") == "neoforge:can_item_perform_ability":
        return {"type": HH + ":can_item_perform_ability", "ability": c["ability"]}
    return c


def loot_fix(o):
    if isinstance(o, dict):
        o = {k: loot_fix(v) for k, v in o.items()}
        if o.get("type") == "neoforge:can_item_perform_ability":
            o = loot_condition(o)
        if o.get("type") == "minecraft:match_tool" and "predicate" in o:
            o["predicate"] = item_predicate(o["predicate"])
        return o
    if isinstance(o, list):
        return [loot_fix(v) for v in o]
    return o


def item_predicate(p):
    p = dict(p)
    if "tag" in p and "items" not in p:
        p["items"] = "#" + remap_tag(p.pop("tag"))
    if "items" in p:
        v = p["items"]
        if isinstance(v, list):
            p["items"] = [remap_ref(x, "item") if isinstance(x, str) else x for x in v]
        else:
            p["items"] = remap_ref(v, "item")
    return p


def prune_entries(entries):
    out = []
    for e in entries:
        try:
            e = dict(e)
            if e.get("type") == "minecraft:item":
                e["name"] = check_known(remap_item(e["name"]), "item")
            if "children" in e:
                e["children"] = prune_entries(e["children"])
                if not e["children"]:
                    raise Dropped("no children")
            out.append(remap_ids_in(e))
        except Dropped as x:
            REPORT["loot entry dropped"].append(str(x))
    return out


def number_provider(v):
    """1.21.1 accepted untyped uniform/binomial number providers; 26.3 needs the type."""
    if isinstance(v, dict) and "type" not in v:
        if set(v) == {"min", "max"}:
            return {"type": "minecraft:uniform", **v}
        if set(v) == {"n", "p"}:
            return {"type": "minecraft:binomial", **v}
    return v


def fix_number_providers(t):
    for p in t.get("pools", []):
        for k in ("rolls", "bonus_rolls"):
            if k in p:
                p[k] = number_provider(p[k])

    def fns(o):
        if isinstance(o, dict):
            if o.get("function") in ("minecraft:set_count", "minecraft:set_damage", "minecraft:enchant_with_levels"):
                for k in ("count", "damage", "levels"):
                    if k in o:
                        o[k] = number_provider(o[k])
            for v in o.values():
                fns(v)
        elif isinstance(o, list):
            for v in o:
                fns(v)
    fns(t)
    return t


def loot_table(t):
    t = fix_number_providers(conditions_to_fabric(copy.deepcopy(t)))
    for p in t.get("pools", []):
        p.pop("name", None)
        p["entries"] = prune_entries(p["entries"])
    t["pools"] = [p for p in t.get("pools", []) if p["entries"]]
    out = dm.loot_table(t)
    return loot_fix(remap_ids_in(out))


def advancement(a):
    a = conditions_to_fabric(copy.deepcopy(a))
    for crit in a.get("criteria", {}).values():   # placed_block / item_used_on_block "location" lists
        c = crit.get("conditions", {})
        if isinstance(c.get("location"), list):
            c["location"] = dm.conditions(c["location"])
    a = dm.advancement(a)
    s = json.dumps(a)
    for k, v in ADVANCEMENT_ITEMS.items():
        s = s.replace('"%s"' % k, '"%s"' % v)
    a = json.loads(s)
    for c in a.get("criteria", {}).values():   # de-dup item lists after the trellis merge
        for it in c.get("conditions", {}).get("items", []) if isinstance(c.get("conditions", {}).get("items"), list) else []:
            if isinstance(it, dict) and isinstance(it.get("items"), list):
                it["items"] = list(dict.fromkeys(it["items"]))

    def preds(o):
        if isinstance(o, dict):
            if ("items" in o and not isinstance(o["items"], list) or isinstance(o.get("items"), list) and all(isinstance(x, str) for x in o["items"])) or "tag" in o:
                if set(o) <= {"items", "tag", "count", "components", "predicates", "durability"}:
                    o = item_predicate(o)
            return {k: preds(v) for k, v in o.items()}
        if isinstance(o, list):
            return [preds(v) for v in o]
        return o
    a = preds(a)
    # criteria: drop item criteria naming dropped items; keep advancement if any criterion survives
    crits = {}
    for name, c in a.get("criteria", {}).items():
        try:
            crits[name] = remap_ids_in(c)
        except Dropped as e:
            REPORT["advancement criterion dropped"].append(str(e))
    if not crits:
        raise Dropped("no criteria")
    if "requirements" in a:
        reqs = [[x for x in r if x in crits] for r in a["requirements"]]
        a["requirements"] = [r for r in reqs if r]
    a["criteria"] = crits
    if "display" in a and "icon" in a["display"]:
        ic = a["display"]["icon"]
        ic["id"] = remap_item(ic["id"])
        if ic.get("count") == 1:
            del ic["count"]
    return a


# ----------------------------------------------------------------------------- tags

def tag_values(values, kind, registry_known):
    out = []
    for v in values:
        req = True
        if isinstance(v, dict):
            req = v.get("required", True)
            v = v["id"]
        try:
            if v.startswith("#"):
                nv = "#" + remap_tag(v[1:])
            elif kind == "item":
                nv = remap_item(v)
            elif kind == "block":
                nv = remap_block(v)
            elif kind == "fluid":
                nv = FLUID_REMAP.get(v, v.replace("farmersdelight:", HH + ":"))
            else:
                nv = v.replace("farmersdelight:", HH + ":")
            if registry_known is not None and not nv.startswith("#") and nv not in registry_known:
                if req:
                    raise Dropped(nv)
            out.append(nv if req else {"id": nv, "required": False})
        except Dropped as e:
            REPORT["tag value dropped (%s)" % kind].append(str(e))
    # de-dup preserving order
    seen, res = set(), []
    for v in out:
        key = json.dumps(v)
        if key not in seen:
            seen.add(key)
            res.append(v)
    return res


# ----------------------------------------------------------------------------- worldgen

def wg_placed_inline(pf):
    """1.21.1 inline placed feature {feature: {type, config}, placement} -> 26.3."""
    return {"feature": wg_feature(pf["feature"]), "placement": [m for m in wm.placement(pf.get("placement", [])) if m["type"] != "farmersdelight:biome_tag"]}


def remap_states(o):
    if isinstance(o, dict):
        o = {k: remap_states(v) for k, v in o.items()}
        if "Name" in o and isinstance(o["Name"], str):
            o["Name"] = remap_block(o["Name"])
        return o
    if isinstance(o, list):
        return [remap_states(v) for v in o]
    return o


def wg_feature(f):
    t, cfg = f["type"], remap_states(f.get("config", {}))
    if t == "minecraft:simple_block":
        return wm.simple_feature({"type": t, "config": cfg})
    if t in ("farmersdelight:wild_crop",):
        out = {"type": HH + ":wild_crop", "tries": cfg["tries"], "xz_spread": cfg["xz_spread"], "y_spread": cfg["y_spread"],
               "primary_feature": wg_placed_inline(cfg["primary_feature"]),
               "secondary_feature": wg_placed_inline(cfg["secondary_feature"])}
        if "floor_feature" in cfg:
            out["floor_feature"] = wg_placed_inline(cfg["floor_feature"])
        return out
    if t in (HH + ":salt_cave", HH + ":nest"):
        return {"type": t}
    raise ValueError("unhandled feature %s" % t)


SANDY_SHRUB_STANDIN = "minecraft:short_dry_grass"


def migrate_worldgen(src_dirs, out):
    patches = {}
    for d in src_dirs:
        cf = os.path.join(d, "configured_feature")
        if not os.path.isdir(cf):
            continue
        for fn in sorted(os.listdir(cf)):
            src = json.load(open(os.path.join(cf, fn)))
            s = json.dumps(src).replace('"farmersdelight:sandy_shrub"', '"%s"' % SANDY_SHRUB_STANDIN)
            src = json.loads(s)
            t, cfg = src["type"], src["config"]
            name = fn[:-5]
            if t in ("minecraft:flower", "minecraft:random_patch"):
                inner = remap_states(cfg["feature"])
                feat = wm.simple_feature(inner["feature"])
                patches[name] = [
                    {"type": "minecraft:count", "count": cfg["tries"]},
                    {"type": "minecraft:offset", "x": wm.TRAPEZOID(cfg["xz_spread"]), "y": wm.TRAPEZOID(cfg["y_spread"]), "z": wm.TRAPEZOID(cfg["xz_spread"])},
                ] + wm.placement(inner.get("placement", []))
            else:
                feat = wg_feature(src)
            write(os.path.join(out, "worldgen/feature", fn), feat)
        pf = os.path.join(d, "placed_feature")
        for fn in sorted(os.listdir(pf)):
            src = json.load(open(os.path.join(pf, fn)))
            feat = src["feature"].replace("farmersdelight:", HH + ":")
            mods = [m for m in wm.placement(src["placement"]) if m["type"] != "farmersdelight:biome_tag"]
            key = feat.split(":", 1)[1]
            if key in patches:
                mods = mods + patches[key]
            write(os.path.join(out, "worldgen/placed_feature", fn), {"feature": feat, "placement": mods})


# ----------------------------------------------------------------------------- structure NBT

def migrate_structure(src, dst):
    import nbtlib
    from nbtlib import Compound, String, Int, Byte, List
    f = nbtlib.load(src)
    pal = f["palette"]
    new_pal = []
    extra_be = {}  # palette index -> block entity nbt to add/replace

    def st(name, props=None):
        c = Compound({"Name": String(name)})
        if props:
            c["Properties"] = Compound({k: String(v) for k, v in props.items()})
        return c

    for idx, p in enumerate(pal):
        name = str(p["Name"])
        props = {k: str(v) for k, v in p.get("Properties", {}).items()}
        if name in ("hearthandharvest:trellis", "hearthandharvest:grape_trellis"):
            sides = [d for d in ("north", "south", "east", "west") if props.get("side_" + d) == "true"]
            if props.get("middle_ns") == "true":
                sides.append("east")
            if props.get("middle_ew") == "true":
                sides.append("north")
            plant = props.get("plant", "none")
            if not sides:
                # flat (floor/roof) trellis only: BF trellises are wall panels
                new_pal.append(st("minecraft:oak_trapdoor", {"facing": "north", "half": "bottom", "open": "false", "powered": "false", "waterlogged": "false"}))
                continue
            new_pal.append(st("bountifulfares:trellis", {"facing": sides[0], "waterlogged": "false"}))
            be = Compound({"id": String("bountifulfares:trellis_block_entity")})
            item = {"vine": "minecraft:vine", "rose": "minecraft:rose_bush", "red_grape": "hearthandharvest:red_grapes",
                    "green_grape": "hearthandharvest:green_grapes"}.get(plant)
            if item:
                be["Plant"] = Compound({"id": String(item), "count": Int(1)})
                if "grape" in plant:
                    # HH grape age 0..4 (ripe at 4) -> BF stage 0..5 (ripe at stages=5)
                    age = int(props.get("age", "0"))
                    be["Stage"] = Int(5 if age >= 4 else age)
            extra_be[idx] = be
            REPORT["structure trellis"].append("%s %s -> facing %s plant %s" % (name, sides, sides[0], plant))
            continue
        if name.startswith("farmersdelight:"):
            path = name.split(":", 1)[1]
            standins = {
                "stove": ("minecraft:smoker", {"facing": props.get("facing", "north"), "lit": "false"}),
                "tatami": ("minecraft:bamboo_mosaic", None),
                "rope_fence": ("minecraft:oak_fence", props),
                "purple_canvas_wall_sign": ("minecraft:pale_oak_wall_sign", props),
                "pink_canvas_wall_sign": ("minecraft:cherry_wall_sign", props),
                "wooden_basket": ("minecraft:barrel", {"facing": props.get("facing", "up"), "open": "false"}),
            }
            if path in standins:
                n, pr = standins[path]
                new_pal.append(st(n, pr))
                REPORT["structure stand-in"].append("%s -> %s" % (name, n))
                continue
            if path in HH_BLOCKS:
                new_pal.append(st(HH + ":" + path, props))
                continue
            raise ValueError("unhandled structure block " + name)
        if name.startswith(HH + ":") and name.split(":")[1] not in HH_BLOCKS:
            raise ValueError("structure block not registered: " + name)
        new_pal.append(p)
    f["palette"] = List[Compound](new_pal)

    be_ids = {"farmersdelight:cutting_board": HH + ":cutting_board", "farmersdelight:cabinet": HH + ":cabinet",
              "farmersdelight:basket": "minecraft:barrel", "farmersdelight:canvas_sign": "minecraft:sign",
              "farmersdelight:stove": None}
    for b in f["blocks"]:
        s = int(b["state"])
        if s in extra_be:
            b["nbt"] = copy.deepcopy(extra_be[s])
            continue
        n = b.get("nbt")
        if n is None:
            continue
        bid = str(n.get("id"))
        if bid in be_ids:
            if be_ids[bid] is None:
                del b["nbt"]
                continue
            n["id"] = String(be_ids[bid])
            if bid == "farmersdelight:basket":
                for k in list(n.keys()):
                    if k not in ("id", "LootTable", "LootTableSeed", "Items"):
                        del n[k]
        _remap_nbt_items(n)
    with gzip.GzipFile(dst, "wb", mtime=0) as g:   # deterministic output (no timestamp)
        f.write(g)


def _remap_nbt_items(n):
    from nbtlib import String
    if isinstance(n, dict):
        for k, v in n.items():
            if k == "id" and isinstance(v, str) and ("count" in n or "Count" in n):
                try:
                    n[k] = String(remap_item(str(v)))
                except Dropped:
                    pass
            else:
                _remap_nbt_items(v)
    elif isinstance(n, list):
        for v in n:
            _remap_nbt_items(v)


# ----------------------------------------------------------------------------- io helpers

WRITTEN = {}


def write(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        json.dump(obj, fh, indent=2)
        fh.write("\n")
    WRITTEN[path] = obj


def walk_json(root):
    for r, _, files in os.walk(root):
        for fn in sorted(files):
            if fn.endswith(".json"):
                p = os.path.join(r, fn)
                yield os.path.relpath(p, root), p


def java_ids(path, pattern):
    src = open(path).read()
    return set(re.findall(pattern, src))


# ----------------------------------------------------------------------------- main

def main(hh, fdr, fd121, port, vanilla, *extra_tag_dirs):
    res = os.path.join(port, "src/main/resources")
    gen = os.path.join(port, "src/main/generated")
    out = os.path.join(res, "data")
    java = os.path.join(port, "src/main/java/alabaster/hearthandharvest")

    reg = r'register[A-Za-z]*\(\s*"([a-z0-9_/]+)"'
    HH_ITEMS.update(java_ids(os.path.join(java, "common/registry/HHModItems.java"), reg))
    HH_BLOCKS.update(java_ids(os.path.join(java, "common/registry/HHModBlocks.java"), r'\(\s*"([a-z0-9_/]+)"'))
    FLUIDS.update(java_ids(os.path.join(java, "common/registry/HHModFluids.java"), r'register\(\s*"([a-z0-9_]+)"'))
    KNOWN_ITEMS.update(HH + ":" + i for i in HH_ITEMS)
    KNOWN_BLOCKS.update(HH + ":" + b for b in HH_BLOCKS)
    for f in os.listdir(os.path.join(vanilla, "assets/minecraft/items")):
        KNOWN_ITEMS.add("minecraft:" + f[:-5])
    for f in os.listdir(os.path.join(vanilla, "assets/minecraft/blockstates")):
        KNOWN_BLOCKS.add("minecraft:" + f[:-5])
    for base in (res, gen):
        for ns in ("bountifulfares", "flavored"):
            d = os.path.join(base, "assets", ns, "items")
            if os.path.isdir(d):
                KNOWN_ITEMS.update(ns + ":" + f[:-5] for f in os.listdir(d))
            d = os.path.join(base, "assets", ns, "blockstates")
            if os.path.isdir(d):
                KNOWN_BLOCKS.update(ns + ":" + f[:-5] for f in os.listdir(d))
            lang = os.path.join(base, "assets", ns, "lang/en_us.json")
            if os.path.exists(lang):
                for k in json.load(open(lang)):
                    parts = k.split(".")
                    if len(parts) == 3 and parts[0] == "item" and parts[1] == ns:
                        KNOWN_ITEMS.add(ns + ":" + parts[2])
    # vanilla items that are not in assets/items (none expected) + air
    KNOWN_ITEMS.add("minecraft:air")

    kept_recipes = set()
    recipe_conditions = {}   # conditional recipe -> its conditions (its recipe advancement gets them too)
    hh_roots = [os.path.join(hh, "src/generated/resources/data"), os.path.join(hh, "src/main/resources/data")]

    # ---- HH recipes
    for root in hh_roots:
        for rel, p in walk_json(root):
            ns, kind_rel = rel.split(os.sep, 1)
            kind = kind_rel.split(os.sep)[0]
            if kind != "recipe":
                continue
            rid = kind_rel[len("recipe/"):-5]
            if rid in SKIP_RECIPES:
                REPORT["recipe skipped (dup)"].append(rel)
                continue
            try:
                r = recipe(json.load(open(p)))
            except Dropped as e:
                REPORT["recipe dropped"].append("%s (%s)" % (rel, e))
                continue
            write(os.path.join(out, ns, kind_rel), r)
            kept_recipes.add(ns + ":" + rid)
            if "fabric:load_conditions" in r:
                recipe_conditions[ns + ":" + rid] = r["fabric:load_conditions"]

    # ---- FD (FDR 26.3) recipes for the ported FD pieces
    fdr_data = os.path.join(fdr, "src/generated/resources/data/farmersdelight")
    for rel, p in walk_json(os.path.join(fdr_data, "recipe")):
        if rel.startswith("salvaging"):
            continue
        r = json.load(open(p))
        try:
            r2 = fdr_recipe(r)
        except Dropped as e:
            REPORT["fd recipe skipped"].append("%s (%s)" % (rel, e))
            continue
        rid = HH + ":" + rel[:-5]
        if os.path.join(out, HH, "recipe", rel) in WRITTEN:
            REPORT["fd recipe clashes with hh"].append(rel)
            continue
        write(os.path.join(out, HH, "recipe", rel), r2)
        kept_recipes.add(rid)

    # ---- advancements (HH only; FD's advancement tree is not part of the bundle)
    for root in hh_roots:
        for rel, p in walk_json(root):
            ns, kind_rel = rel.split(os.sep, 1)
            if not kind_rel.startswith("advancement"):
                continue
            a = json.load(open(p))
            if kind_rel.startswith("advancement/recipes/"):
                rec = a["rewards"]["recipes"][0] if a.get("rewards", {}).get("recipes") else None
                if rec and rec not in kept_recipes:
                    REPORT["recipe advancement dropped"].append(rel)
                    continue
            try:
                a = advancement(a)
            except Dropped as e:
                REPORT["advancement dropped"].append("%s (%s)" % (rel, e))
                continue
            rec = (a.get("rewards", {}).get("recipes") or [None])[0]
            if rec in recipe_conditions and "fabric:load_conditions" not in a:
                a = {"fabric:load_conditions": recipe_conditions[rec], **a}
            write(os.path.join(out, ns, kind_rel), a)

    # ---- loot tables
    for root in hh_roots:
        for rel, p in walk_json(root):
            ns, kind_rel = rel.split(os.sep, 1)
            if not kind_rel.startswith("loot_table"):
                continue
            if kind_rel.startswith("loot_table/blocks/"):
                b = kind_rel[len("loot_table/blocks/"):-5]
                if b not in HH_BLOCKS:
                    REPORT["block loot skipped (block not registered)"].append(b)
                    continue
            write(os.path.join(out, ns, kind_rel), loot_table(json.load(open(p))))
    for rel, p in walk_json(os.path.join(fdr_data, "loot_table/blocks")):
        b = rel[:-5]
        if b not in HH_BLOCKS:
            continue
        dst = os.path.join(out, HH, "loot_table/blocks", rel)
        if dst in WRITTEN:
            continue
        t = json.loads(json.dumps(json.load(open(p))).replace("farmersdelight:", HH + ":"))
        write(dst, t)

    # ---- tags
    tag_files = collections.defaultdict(lambda: {"replace": False, "values": []})
    tag_sources = [(r, False) for r in hh_roots] + [(os.path.join(fdr, "src/generated/resources/data"), True),
                                                    (os.path.join(fdr, "src/main/resources/data"), True)]
    for root, is_fd in tag_sources:
        for rel, p in walk_json(root):
            ns, kind_rel = rel.split(os.sep, 1)
            if not kind_rel.startswith("tags/"):
                continue
            if ns in ("origins", "tconstruct", "createaddition", "sable") and is_fd:
                continue
            reg_kind = kind_rel.split(os.sep)[1]
            if reg_kind == "worldgen":
                reg_kind = "biome"
            if is_fd and reg_kind in ("villager_trade", "damage_type"):
                continue
            tns = HH if ns == "farmersdelight" else ns
            kind = {"item": "item", "block": "block", "fluid": "fluid"}.get(reg_kind, reg_kind)
            known = KNOWN_ITEMS if kind == "item" else KNOWN_BLOCKS if kind == "block" else None
            data = json.load(open(p))
            vals = tag_values(data.get("values", []), kind, known if is_fd else (known if kind in ("item", "block") else None))
            if not vals:
                continue
            key = os.path.join(tns, kind_rel)
            tag_files[key]["values"] += [v for v in vals if v not in tag_files[key]["values"]]
    # Decision 16: Flavored's knife is a knife (cutting board, straw); decision 5: corn and maize interchangeable.
    tag_files[os.path.join("c", "tags/item/tools/knife.json")]["values"].append("flavored:knife")
    tag_files[os.path.join("c", "tags/item/vegetables/corn.json")]["values"].append("bountifulfares:maize")
    tag_files[os.path.join("c", "tags/item/foods/corn.json")]["values"].append("#c:vegetables/corn")
    tag_files[os.path.join("c", "tags/item/flours/wheat.json")]  # (bountifulfares:flour via remap)
    tag_files[os.path.join("c", "tags/block/villager_farmlands.json")]["values"] += ["minecraft:farmland", HH + ":rich_soil_farmland"]
    # Tags the ported code uses that 1.21.1 didn't ship as data:
    # decision 12 - BF's walnut/palm mulch act as HH mulch (HHModTags.MULCH)
    tag_files[os.path.join(HH, "tags/block/mulch.json")]["values"] += [
        HH + ":mulch", "bountifulfares:walnut_mulch", "bountifulfares:walnut_mulch_block",
        "bountifulfares:palm_mulch", "bountifulfares:palm_mulch_block"]
    # decision 10 - BF Jack o' Straws scare crows too
    tag_files[os.path.join(HH, "tags/block/repels_crows.json")]["values"].append("#bountifulfares:jack_o_straws")
    # decision 11 - HH's flour bag is BF's flour block (HHCommonTags storage_blocks/flour)
    for kind in ("block", "item"):
        tag_files[os.path.join("c", "tags/%s/storage_blocks/flour.json" % kind)]["values"].append("bountifulfares:flour_block")
    # decision 8 - the bundle's other alcoholic drinks (they give HH's Drunk too)
    tag_files[os.path.join("c", "tags/item/drinks/alcohol.json")]["values"] += [
        "flavored:beer", "flavored:cider", "bountifulfares:elderberry_wine_bottle", "bountifulfares:lapisberry_wine_bottle"]
    # FD's knife-mineable blocks (FDTags.MINEABLE_WITH_KNIFE is c:mineable/knife)
    tag_files[os.path.join("c", "tags/block/mineable/knife.json")]["values"].append("#" + HH + ":mineable/knife")
    knife = tag_files[os.path.join(HH, "tags/block/mineable/knife.json")]
    knife["values"] = [v for v in knife["values"] if v != "#c:mineable/knife"]   # would be a cycle now

    # Drop references to tags that won't exist (FD tags emptied by the filtering, e.g. FD knives),
    # and enchantment tag entries for FD enchantments that aren't part of the bundle. Repeat until stable.
    existing_tags = set()
    for base in (os.path.join(vanilla, "data"), os.path.join(res, "data"), os.path.join(gen, "data")) + tuple(extra_tag_dirs):
        if not os.path.isdir(base):
            continue
        for nsd in os.listdir(base):
            troot = os.path.join(base, nsd, "tags")
            for rel, _ in walk_json(troot) if os.path.isdir(troot) else []:
                parts = rel.split(os.sep)
                kind = "worldgen/" + parts[1] if parts[0] == "worldgen" else parts[0]
                sub = parts[2:] if parts[0] == "worldgen" else parts[1:]
                existing_tags.add((kind, nsd + ":" + "/".join(sub)[:-5]))
    enchantments = {"minecraft:" + f[:-5] for f in os.listdir(os.path.join(vanilla, "data/minecraft/enchantment"))}
    for base in (res, gen):
        for nsd in ("bountifulfares", "flavored"):
            d = os.path.join(base, "data", nsd, "enchantment")
            if os.path.isdir(d):
                enchantments.update(nsd + ":" + f[:-5] for f in os.listdir(d))
    enchantments.update(HH + ":" + f[:-5] for f in os.listdir(os.path.join(hh, "src/main/resources/data", HH, "enchantment")))

    def tag_id(key):
        ns, rest = key.split(os.sep, 1)
        parts = rest.split(os.sep)[1:]
        if parts[0] == "worldgen":
            return "worldgen/" + parts[1], ns + ":" + "/".join(parts[2:])[:-5]
        return parts[0], ns + ":" + "/".join(parts[1:])[:-5]
    changed = True
    while changed:
        changed = False
        ours = {tag_id(k) for k, t in tag_files.items() if t["values"]}
        for key, t in tag_files.items():
            kind, _ = tag_id(key)
            keep = []
            for v in t["values"]:
                vid = v["id"] if isinstance(v, dict) else v
                req = not (isinstance(v, dict) and not v.get("required", True))
                if vid.startswith("#") and req and (kind, vid[1:]) not in ours and (kind, vid[1:]) not in existing_tags:
                    REPORT["tag reference dropped (tag missing)"].append("%s in %s" % (vid, key))
                    changed = True
                    continue
                if kind == "enchantment" and not vid.startswith("#") and vid not in enchantments:
                    REPORT["tag value dropped (enchantment)"].append(vid)
                    changed = True
                    continue
                keep.append(v)
            t["values"] = keep

    collisions = []
    for key, t in tag_files.items():
        t["values"] = list({json.dumps(v, sort_keys=True): v for v in t["values"]}.values())
        if not t["values"]:
            continue
        dst = os.path.join(out, key)
        gdst = os.path.join(gen, "data", key)
        if os.path.exists(gdst):
            collisions.append(key)
            continue
        if os.path.exists(dst) and dst not in WRITTEN:
            existing = json.load(open(dst))
            t = {"replace": existing.get("replace", False),
                 "values": existing["values"] + [v for v in t["values"] if v not in existing["values"]]}
        write(dst, t)
    write_tag_additions(os.path.join(port, "src/client/java/alabaster/hearthandharvest/datagen/HHTagAdditions.java"),
                        {k: tag_files[k]["values"] for k in sorted(collisions)})

    # ---- data maps (HH format kept, ids remapped)
    for root in hh_roots:
        dmdir = os.path.join(root, HH, "data_maps")
        if not os.path.isdir(dmdir):
            continue
        for rel, p in walk_json(dmdir):
            d = json.load(open(p))
            vals = {}
            for k, v in d["values"].items():
                try:
                    if rel.startswith("fluid"):
                        k = FLUID_REMAP.get(k, k)
                        vals[k] = remap_item(v if isinstance(v, str) else v["value"])
                    else:
                        vals[remap_item(k)] = v
                except Dropped as e:
                    REPORT["data map entry dropped"].append(str(e))
            write(os.path.join(out, HH, "data_maps", rel), {"values": vals})

    # ---- compostables -> HHCompostables.java
    comp = json.load(open(os.path.join(hh, "src/generated/resources/data/neoforge/data_maps/item/compostables.json")))["values"]
    entries = dict(FD_COMPOSTABLES)
    for k, v in comp.items():
        try:
            i = remap_item(k)
        except Dropped:
            continue
        if i.startswith(HH + ":"):
            entries[i.split(":")[1]] = v["chance"]
    entries = sorted(entries.items())
    write_compostables(os.path.join(java, "common/registry/HHCompostables.java"), entries)

    # ---- enchantments, structures, worldgen
    for rel, p in walk_json(os.path.join(hh, "src/main/resources/data", HH, "enchantment")):
        write(os.path.join(out, HH, "enchantment", rel), json.load(open(p)))
    for sub in ("structure", "structure_set", "template_pool", "processor_list"):
        d = os.path.join(hh, "src/main/resources/data", HH, "worldgen", sub)
        for rel, p in walk_json(d):
            write(os.path.join(out, HH, "worldgen", sub, rel), json.load(open(p)))
    migrate_worldgen([os.path.join(hh, "src/generated/resources/data", HH, "worldgen"),
                      os.path.join(hh, "src/main/resources/data", HH, "worldgen")], os.path.join(out, HH))
    # FD 1.21 wild cabbages/onions (FD's own wild_crop feature, now hearthandharvest:wild_crop)
    fdwg = os.path.join(fd121, "src/generated/resources/data/farmersdelight/worldgen")
    for name in ("patch_wild_cabbages", "patch_wild_onions"):
        src = json.load(open(os.path.join(fdwg, "configured_feature", name + ".json")))
        src = json.loads(json.dumps(src).replace('"farmersdelight:sandy_shrub"', '"%s"' % SANDY_SHRUB_STANDIN))
        write(os.path.join(out, HH, "worldgen/feature", name + ".json"), wg_feature(src))
        pl = json.load(open(os.path.join(fdwg, "placed_feature", name + ".json")))
        write(os.path.join(out, HH, "worldgen/placed_feature", name + ".json"),
              {"feature": pl["feature"].replace("farmersdelight:", HH + ":"),
               "placement": [m for m in wm.placement(pl["placement"]) if m["type"] != "farmersdelight:biome_tag"]})
    for tn in ("has_wild_cabbage", "wild_onions_whitelist", "wild_onions_blacklist"):
        for cand in (os.path.join(fd121, "src/main/resources/data/farmersdelight/tags/worldgen/biome", tn + ".json"),
                     os.path.join(fd121, "src/generated/resources/data/farmersdelight/tags/worldgen/biome", tn + ".json"),
                     os.path.join(fdr, "src/main/resources/data/farmersdelight/tags/worldgen/biome", tn + ".json")):
            if os.path.exists(cand):
                write(os.path.join(out, HH, "tags/worldgen/biome", tn + ".json"), json.load(open(cand)))
                break
        else:
            REPORT["missing biome tag"].append(tn)
    os.makedirs(os.path.join(out, HH, "structure"), exist_ok=True)
    migrate_structure(os.path.join(hh, "src/main/resources/data", HH, "structure/lilliput_lane.nbt"),
                      os.path.join(out, HH, "structure/lilliput_lane.nbt"))

    # ---- villager trades (1.21.1 VillagerEvents)
    trades(out)

    for k, v in sorted(REPORT.items()):
        print("== %s (%d)" % (k, len(v)))
        for x in sorted(set(v)):
            print("   ", x)
    print("tag path collisions with datagen output:", collisions)
    print("written:", len(WRITTEN))


def fdr_recipe(r):
    """FDR 26.3 recipe -> bundle: ids remapped; skipped if its result isn't a ported FD/HH item."""
    r = copy.deepcopy(r)
    orig_ings = {k: r[k] for k in ("key", "ingredients", "ingredient") if k in r}
    if r["type"].startswith("farmersdelight:"):
        r["type"] = r["type"].replace("farmersdelight:", HH + ":")
    if r["type"] not in ("minecraft:crafting_shaped", "minecraft:crafting_shapeless", "minecraft:smelting",
                         "minecraft:smoking", "minecraft:campfire_cooking", HH + ":cooking", HH + ":cutting"):
        raise Dropped("type " + r["type"])

    def ing(i):
        if isinstance(i, list):
            return [ing(x) for x in i]
        if isinstance(i, dict):
            if i.get("fabric:type") == "farmersdelight:item_ability":
                return {"fabric:type": HH + ":item_ability", "action": i["action"]}
            raise Dropped("custom ingredient %r" % i)
        return check_known(remap_ref(i, "item"), "item")
    if "key" in r:
        r["key"] = {k: ing(v) for k, v in r["key"].items()}
    for k in ("ingredient", "tool"):
        if k in r:
            r[k] = ing(r[k])
    if "ingredients" in r:
        r["ingredients"] = [ing(x) for x in r["ingredients"]]
    if r["type"] == HH + ":cutting":
        outs = []
        for res in r["result"]:
            try:
                res = dict(res)
                res["item"] = stack(res["item"])
                outs.append(res)
            except Dropped as e:
                REPORT["fd cutting result dropped"].append(str(e))
        if not outs:
            raise Dropped("no results")
        r["result"] = outs
        return r
    res = stack(r["result"])
    # Keep FD recipes making a ported FD item, or using one (canvas -> paper, bark -> compost, ...).
    uses_fd = '"farmersdelight:' in json.dumps(orig_ings) and any(
        ("hearthandharvest:" + x) in json.dumps({k: r[k] for k in ("key", "ingredients", "ingredient") if k in r})
        for x in re.findall(r'farmersdelight:([a-z0-9_/]+)', json.dumps(orig_ings)))
    if not res["id"].startswith(HH + ":") and not uses_fd:
        raise Dropped("result %s not an FD item of the bundle" % res["id"])
    r["result"] = res
    if "container" in r:
        r["container"] = stack(r["container"])
    return r


def write_tag_additions(path, tags):
    """Tags whose file Bountiful Fares' datagen also writes (src/main/generated): one jar can hold only
    one file per path, so BF's tag providers add HH's entries (BFItemTagProvider/BFBlockTagProvider)."""
    by_kind = {"item": [], "block": []}
    for key, values in tags.items():
        ns, rest = key.split(os.sep, 1)
        parts = rest.split(os.sep)            # tags/<kind>/<path...>.json
        kind = parts[1]
        tag = ns + ":" + "/".join(parts[2:])[:-5]
        by_kind[kind].append((tag, values))
    lines = ["package alabaster.hearthandharvest.datagen;", "",
             "import net.minecraft.core.registries.Registries;",
             "import net.minecraft.data.tags.TagAppender;",
             "import net.minecraft.resources.Identifier;",
             "import net.minecraft.resources.ResourceKey;",
             "import net.minecraft.tags.TagKey;",
             "import net.minecraft.world.item.Item;",
             "import net.minecraft.world.level.block.Block;", "",
             "import java.util.function.Function;", "",
             "/**",
             " * Hearth and Harvest (+ its Farmer's Delight pieces) entries of common/vanilla tags that Bountiful",
             " * Fares' datagen also writes. A jar holds one file per path, so BF's tag providers add these.",
             " * Generated by {@code _porting_tools/hh_data_migrate.py}.",
             " */",
             "public final class HHTagAdditions {",
             "    private HHTagAdditions() {", "    }", ""]
    for kind, cls, reg in (("item", "Item", "ITEM"), ("block", "Block", "BLOCK")):
        lines.append("    public static void add%sTags(Function<TagKey<%s>, TagAppender<%s>> builder) {" % (cls, cls, cls))
        for tag, values in sorted(by_kind[kind]):
            lines.append('        builder.apply(TagKey.create(Registries.%s, Identifier.parse("%s")))' % (reg, tag))
            for v in values:
                opt = False
                if isinstance(v, dict):
                    opt, v = not v.get("required", True), v["id"]
                if v.startswith("#"):
                    lines.append('                .addOptionalTag(TagKey.create(Registries.%s, Identifier.parse("%s")))' % (reg, v[1:]))
                else:
                    lines.append('                .%s(ResourceKey.create(Registries.%s, Identifier.parse("%s")))' % ("addOptional" if opt else "add", reg, v))
            lines[-1] += ";"
        lines += ["    }", ""]
    lines += ["}", ""]
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write("\n".join(lines))


def write_compostables(path, entries):
    lines = ["package alabaster.hearthandharvest.common.registry;", "",
             "import alabaster.hearthandharvest.HearthAndHarvest;",
             "import net.fabricmc.fabric.api.item.v1.DefaultItemComponentEvents;",
             "import net.hecco.bountifulfares.registry.util.BFRegistries;",
             "import net.minecraft.core.component.DataComponents;",
             "import net.minecraft.core.registries.BuiltInRegistries;",
             "import net.minecraft.world.item.component.Compostable;", "",
             "import java.util.LinkedHashMap;",
             "import java.util.Map;", "",
             "/**",
             " * Hearth and Harvest's composter chances (1.21.1: the NeoForge {@code compostables} data map) and",
             " * those of the Farmer's Delight items it now carries (FarmersDelightRefabricated's CompostableHelper).",
             " * 26.3 stores compostability as the {@code minecraft:compostable} item component; chances map onto",
             " * vanilla's tiers like Bountiful Fares' own (BFRegistries.compostBucketFor).",
             " * Generated by {@code _porting_tools/hh_data_migrate.py}; merged items are left to their own mod.",
             " */",
             "public final class HHCompostables {",
             "    private static final Map<String, Float> CHANCES = new LinkedHashMap<>();", "",
             "    static {"]
    for name, chance in sorted(entries):
        lines.append('        CHANCES.put("%s", %sF);' % (name, repr(float(chance))))
    lines += ["    }", "",
              "    private HHCompostables() {", "    }", "",
              "    public static void register() {",
              "        DefaultItemComponentEvents.MODIFY.register(context -> CHANCES.forEach((path, chance) ->",
              "                context.modify(BuiltInRegistries.ITEM.getValue(HearthAndHarvest.id(path)),",
              "                        builder -> builder.set(DataComponents.COMPOSTABLE, new Compostable(BFRegistries.compostBucketFor(chance))))));",
              "    }", "}", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(lines))


# FarmersDelightRefabricated 26.3 CompostableHelper entries for the FD items HH now registers.
FD_COMPOSTABLES = {"cabbage": 0.65, "cabbage_leaf": 0.5, "cabbage_seeds": 0.3, "onion": 0.65, "pie_crust": 0.65,
                   "straw": 0.3, "tree_bark": 0.3, "wild_cabbages": 0.65, "wild_onions": 0.65}


def trades(out):
    def buy(item, count, max_uses, xp):  # emeraldForItemsTrade
        return {"gives": {"id": "minecraft:emerald"}, "max_uses": max_uses, "reputation_discount": 0.05,
                "wants": {"count": count, "id": item}, "xp": xp}

    def sell(price, item, count, max_uses, xp):  # itemForEmeraldTrade
        g = {"id": item}
        if count != 1:
            g = {"count": count, "id": item}
        w = {"id": "minecraft:emerald"} if price == 1 else {"count": price, "id": "minecraft:emerald"}
        return {"gives": g, "max_uses": max_uses, "reputation_discount": 0.05, "wants": w, "xp": xp}

    hh = lambda p: HH + ":" + p
    farmer = {
        1: [("blueberries_emerald", buy(hh("blueberries"), 26, 16, 2)), ("raspberry_emerald", buy(hh("raspberry"), 26, 16, 2)),
            ("cherry_emerald", buy(hh("cherry"), 10, 16, 2)), ("peanut_emerald", buy(hh("peanut"), 16, 16, 2)),
            ("cotton_emerald", buy(hh("cotton"), 16, 16, 2)), ("emerald_manure", sell(2, hh("manure"), 8, 16, 2)),
            # Farmer's Delight's farmer trade for onions (cabbages at level 2); tomatoes are Flavored's here
            ("onion_emerald", buy(hh("onion"), 26, 16, 2))],
        2: [("corn_emerald", buy(hh("corn"), 24, 16, 5)), ("red_grapes_emerald", buy(hh("red_grapes"), 24, 16, 5)),
            ("green_grapes_emerald", buy(hh("green_grapes"), 24, 16, 5)), ("cabbage_emerald", buy(hh("cabbage"), 16, 16, 5))],
        3: [("emerald_scarecrow", sell(8, hh("scarecrow"), 1, 8, 24)), ("emerald_nest", sell(3, hh("nest"), 1, 32, 20)),
            ("emerald_sprinkler", sell(4, hh("sprinkler"), 1, 10, 24))],
        4: [("emerald_farmers_hat", sell(4, hh("farmers_hat"), 1, 8, 30)), ("emerald_pitchfork", sell(4, hh("pitchfork"), 1, 8, 30))],
    }
    mason = {2: [("emerald_manure_bricks", sell(1, hh("manure_bricks"), 8, 16, 5)),
                 ("emerald_polished_manure", sell(1, hh("polished_manure"), 8, 16, 5))]}
    wanderer = [("emerald_" + i, sell(1, hh(i), 1, 1, 12)) for i in
                ("red_grapes", "green_grapes", "blueberries", "raspberry", "peanut", "cotton_seeds", "corn_kernels")]
    wanderer += [("emerald_" + c + "_mum", sell(1, hh(c + "_mum"), 4, 8, 12)) for c in
                 ("yellow", "orange", "red", "blue", "light_blue", "purple", "pink", "white")]
    # fd 26.3 farmer trade values for cabbage (count 16 at level 2): FDR villager_trade/farmer/2/cabbage_emerald
    for prof, levels in (("farmer", farmer), ("mason", mason)):
        for lvl, lst in levels.items():
            ids = []
            for name, t in lst:
                for side in ("gives", "wants"):
                    check_known(t[side]["id"], "item")
                write(os.path.join(out, HH, "villager_trade", prof, str(lvl), name + ".json"), t)
                ids.append("%s:%s/%d/%s" % (HH, prof, lvl, name))
            write(os.path.join(out, "minecraft/tags/villager_trade", prof, "level_%d.json" % lvl), {"replace": False, "values": ids})
    ids = []
    for name, t in wanderer:
        check_known(t["gives"]["id"], "item")
        write(os.path.join(out, HH, "villager_trade/wandering_trader", name + ".json"), t)
        ids.append("%s:wandering_trader/%s" % (HH, name))
    common = os.path.join(out, "minecraft/tags/villager_trade/wandering_trader/common.json")
    existing = json.load(open(common)) if os.path.exists(common) else {"replace": False, "values": []}
    existing["values"] = [v for v in existing["values"] if not v.startswith(HH + ":")] + ids
    write(common, existing)


if __name__ == "__main__":
    main(*sys.argv[1:])
